In [52]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [53]:
data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [54]:
data.shape

(569, 33)

In [55]:
data.drop(['id', 'Unnamed: 32'], axis = 1, inplace= True)

In [56]:
data.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [57]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size= 0.2)

In [58]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [59]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [60]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1])

In [61]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [62]:
y_train_tensor.shape

torch.Size([455])

In [36]:
class simpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        #clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [72]:
import torch.nn as nn
class simpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [73]:
epochs = 500
learning_rate = 0.1

In [74]:
loss_function = nn.BCELoss()

In [76]:
!pip install torch==0.10.1

ERROR: Could not find a version that satisfies the requirement torch==0.10.1 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==0.10.1

In [77]:
import torch
print(torch.__version__)

2.1.2+cu121

In [75]:
model = simpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
for epoch in range(epochs):
    y_pred = model(X_train_tensor)
    loss = loss_function(y_pred, y_train_tensor)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

c:\Users\admin\anaconda3\envs\nlp_transformer\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

InvalidVersion: Invalid version: '0.10.1,<0.11'

In [40]:
model = simpleNN(X_train_tensor)
for epoch in range(epochs):
    #do a forward pass
    y_pred = model.forward(X_train_tensor)
    #calculate the loss
    loss = model.loss_function(y_pred, y_train_tensor)
    #do a back prop
    loss.backward()
    #update the weight
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss 
    print(f'epoch - {epoch + 1}, loss: {loss.item()}')

epoch - 1, loss: 0.5230185461552356
epoch - 2, loss: 0.5082646274452822
epoch - 3, loss: 0.4939631133146857
epoch - 4, loss: 0.4801059165467835
epoch - 5, loss: 0.4666867502766439
epoch - 6, loss: 0.4533282403186138
epoch - 7, loss: 0.43837130404433977
epoch - 8, loss: 0.42389962209461407
epoch - 9, loss: 0.4099103545770715
epoch - 10, loss: 0.3963980192060639
epoch - 11, loss: 0.38335335257286646
epoch - 12, loss: 0.37076293677612415
epoch - 13, loss: 0.35860972344112657
epoch - 14, loss: 0.34687426510064034
epoch - 15, loss: 0.33553625774099516
epoch - 16, loss: 0.3245760000910925
epoch - 17, loss: 0.31397552374664467
epoch - 18, loss: 0.30371932587674144
epoch - 19, loss: 0.2937947566063674
epoch - 20, loss: 0.2841921565208951
epoch - 21, loss: 0.27490483272014016
epoch - 22, loss: 0.26592893031017956
epoch - 23, loss: 0.2572632228905146
epoch - 24, loss: 0.24890882038860926
epoch - 25, loss: 0.24086877964462078
epoch - 26, loss: 0.23314760332790066
epoch - 27, loss: 0.22575062669908405
epoch - 28, loss: 0.21868331624735327
epoch - 29, loss: 0.2119505368608876
epoch - 30, loss: 0.20555587410310452
epoch - 31, loss: 0.19950111450556457
epoch - 32, loss: 0.19378597165058423
epoch - 33, loss: 0.18840809067651762
epoch - 34, loss: 0.18336327501050068
epoch - 35, loss: 0.1786457852463728
epoch - 36, loss: 0.1742485120631061
epoch - 37, loss: 0.1701628656028694
epoch - 38, loss: 0.1663783658182587
epoch - 39, loss: 0.1628821102838309
epoch - 40, loss: 0.15965842722318108
epoch - 41, loss: 0.15668898775016402
epoch - 42, loss: 0.1539534518838483
epoch - 43, loss: 0.15143048614823806
epoch - 44, loss: 0.14909886271259745
epoch - 45, loss: 0.14693838335140386
epoch - 46, loss: 0.14493049670648825
epoch - 47, loss: 0.1430586022879013
epoch - 48, loss: 0.14130810773447383
epoch - 49, loss: 0.13966632601972218
epoch - 50, loss: 0.13812228811432078
epoch - 51, loss: 0.13666652457930753
epoch - 52, loss: 0.1352908486240596
epoch - 53, loss: 0.13398815756488014
epoch - 54, loss: 0.13275225956893144
epoch - 55, loss: 0.1315777267909064
epoch - 56, loss: 0.1304597730721013
epoch - 57, loss: 0.1293941531415226
epoch - 58, loss: 0.12837707997070877
epoch - 59, loss: 0.12740515711631584
epoch - 60, loss: 0.12647532326629723
epoch - 61, loss: 0.12558480664124916
epoch - 62, loss: 0.12473108732041391
epoch - 63, loss: 0.12391186593124123
epoch - 64, loss: 0.12312503745328614
epoch - 65, loss: 0.12236866914320282
epoch - 66, loss: 0.12164098179389839
epoch - 67, loss: 0.12094033370518315
epoch - 68, loss: 0.12026520687302265
epoch - 69, loss: 0.11961419500648689
epoch - 70, loss: 0.11898599306358307
epoch - 71, loss: 0.11837938806750492
epoch - 72, loss: 0.11779325092174092
epoch - 73, loss: 0.11722652924797818
epoch - 74, loss: 0.11667824092150289
epoch - 75, loss: 0.11614746829862976
epoch - 76, loss: 0.11563335300617748
epoch - 77, loss: 0.11513509127108755
epoch - 78, loss: 0.11465192967185633
epoch - 79, loss: 0.1141831613032656
epoch - 80, loss: 0.11372812223213846
epoch - 81, loss: 0.11328618835202796
epoch - 82, loss: 0.11285677245656932
epoch - 83, loss: 0.11243932157713794
epoch - 84, loss: 0.11203331454494826
epoch - 85, loss: 0.1116382597556647
epoch - 86, loss: 0.11125369311716123
epoch - 87, loss: 0.1108791761632563
epoch - 88, loss: 0.11051429431813412
epoch - 89, loss: 0.1101586552977931
epoch - 90, loss: 0.10981188763628337
epoch - 91, loss: 0.10947363932573749
epoch - 92, loss: 0.10914357656029204
epoch - 93, loss: 0.10882138257496529
epoch - 94, loss: 0.10850675657299448
epoch - 95, loss: 0.10819941273805597
epoch - 96, loss: 0.10789907928687495
epoch - 97, loss: 0.10760549763328922
epoch - 98, loss: 0.10731842159843687
epoch - 99, loss: 0.10703761666841916
epoch - 100, loss: 0.10676285930923886
epoch - 101, loss: 0.10649393632950781
epoch - 102, loss: 0.10623064428714676
epoch - 103, loss: 0.10597278893662836
epoch - 104, loss: 0.10572018471361104
epoch - 105, loss: 0.10547265425408016
epoch - 106, loss: 0.10523002794535768
epoch - 107, loss: 0.1049921435065633
epoch - 108, loss: 0.10475884559631224
epoch - 109, loss: 0.10452998544561799
epoch - 110, loss: 0.10430542051413653
epoch - 111, loss: 0.10408501416804007
epoch - 112, loss: 0.10386863537794791
epoch - 113, loss: 0.1036561584354691
epoch - 114, loss: 0.10344746268702683
epoch - 115, loss: 0.10324243228374058
epoch - 116, loss: 0.10304095594623891
epoch - 117, loss: 0.10284292674336384
epoch - 118, loss: 0.10264824188380929
epoch - 119, loss: 0.1024568025198092
epoch - 120, loss: 0.10226851356206004
epoch - 121, loss: 0.1020832835051235
epoch - 122, loss: 0.10190102426261279
epoch - 123, loss: 0.1017216510115183
epoch - 124, loss: 0.10154508204507631
epoch - 125, loss: 0.10137123863362832
epoch - 126, loss: 0.10120004489295967
epoch - 127, loss: 0.10103142766046638
epoch - 128, loss: 0.10086531637766337
epoch - 129, loss: 0.10070164297141589
epoch - 130, loss: 0.10054034175635386
epoch - 131, loss: 0.1003813493309725
epoch - 132, loss: 0.10022460448199373
epoch - 133, loss: 0.10007004809351837
epoch - 134, loss: 0.09991762306068536
epoch - 135, loss: 0.09976727420757288
epoch - 136, loss: 0.0996189482090951
epoch - 137, loss: 0.09947259351666372
epoch - 138, loss: 0.09932816028739976
epoch - 139, loss: 0.09918560031669502
epoch - 140, loss: 0.09904486697393539
epoch - 141, loss: 0.09890591514121065
epoch - 142, loss: 0.09876870115484701
epoch - 143, loss: 0.09863318274960822
epoch - 144, loss: 0.09849931900542216
epoch - 145, loss: 0.09836707029649701
epoch - 146, loss: 0.09823639824270138
epoch - 147, loss: 0.09810726566308943
epoch - 148, loss: 0.09797963653145919
epoch - 149, loss: 0.09785347593384014
epoch - 150, loss: 0.09772875002781073
epoch - 151, loss: 0.09760542600355404
epoch - 152, loss: 0.09748347204656398
epoch - 153, loss: 0.09736285730192049
epoch - 154, loss: 0.09724355184005587
epoch - 155, loss: 0.09712552662394
epoch - 156, loss: 0.09700875347761545
epoch - 157, loss: 0.09689320505601777
epoch - 158, loss: 0.09677885481601986
epoch - 159, loss: 0.09666567698864226
epoch - 160, loss: 0.09655364655237554
epoch - 161, loss: 0.09644273920756226
epoch - 162, loss: 0.09633293135179022
epoch - 163, loss: 0.09622420005625079
epoch - 164, loss: 0.09611652304301806
epoch - 165, loss: 0.09600987866320808
epoch - 166, loss: 0.09590424587597816
epoch - 167, loss: 0.09579960422832973
epoch - 168, loss: 0.09569593383567847
epoch - 169, loss: 0.09559321536315936
epoch - 170, loss: 0.09549143000905337
epoch - 171, loss: 0.09539055948622091
epoch - 172, loss: 0.09529058600054269
epoch - 173, loss: 0.09519149224268411
epoch - 174, loss: 0.0950932613695069
epoch - 175, loss: 0.09499587698916329
epoch - 176, loss: 0.09489932314673254
epoch - 177, loss: 0.09480358431037675
epoch - 178, loss: 0.09470864535799459
epoch - 179, loss: 0.09461449156435317
epoch - 180, loss: 0.09452110858867806
epoch - 181, loss: 0.09442848246268347
epoch - 182, loss: 0.09433659957902442
epoch - 183, loss: 0.09424544668015467
epoch - 184, loss: 0.094155010847574
epoch - 185, loss: 0.09406527949144936
epoch - 186, loss: 0.09397624034059573
epoch - 187, loss: 0.09388788143280231
epoch - 188, loss: 0.09380019110549065
epoch - 189, loss: 0.09371315798669223
epoch - 190, loss: 0.09362677098633301
epoch - 191, loss: 0.09354101928781333
epoch - 192, loss: 0.09345589233987182
epoch - 193, loss: 0.09337137984872304
epoch - 194, loss: 0.09328747177045797
epoch - 195, loss: 0.09320415830369802
epoch - 196, loss: 0.09312142988249292
epoch - 197, loss: 0.09303927716945354
epoch - 198, loss: 0.09295769104911086
epoch - 199, loss: 0.09287666262149302
epoch - 200, loss: 0.09279618319591244
epoch - 201, loss: 0.09271624428495509
epoch - 202, loss: 0.09263683759866513
epoch - 203, loss: 0.09255795503891735
epoch - 204, loss: 0.09247958869397122
epoch - 205, loss: 0.09240173083319943
epoch - 206, loss: 0.09232437390198533
epoch - 207, loss: 0.09224751051678307
epoch - 208, loss: 0.09217113346033441
epoch - 209, loss: 0.09209523567703722
epoch - 210, loss: 0.09201981026845997
epoch - 211, loss: 0.09194485048899735
epoch - 212, loss: 0.09187034974166194
epoch - 213, loss: 0.09179630157400753
epoch - 214, loss: 0.091722699674179
epoch - 215, loss: 0.09164953786708524
epoch - 216, loss: 0.09157681011068995
epoch - 217, loss: 0.09150451049241726
epoch - 218, loss: 0.09143263322566739
epoch - 219, loss: 0.09136117264643936
epoch - 220, loss: 0.0912901232100567
epoch - 221, loss: 0.09121947948799275
epoch - 222, loss: 0.09114923616479255
epoch - 223, loss: 0.09107938803508744
epoch - 224, loss: 0.09100993000070012
epoch - 225, loss: 0.09094085706783651
epoch - 226, loss: 0.09087216434436174
epoch - 227, loss: 0.09080384703715765
epoch - 228, loss: 0.09073590044955895
epoch - 229, loss: 0.09066831997886558
epoch - 230, loss: 0.09060110111392859
epoch - 231, loss: 0.09053423943280743
epoch - 232, loss: 0.09046773060049612
epoch - 233, loss: 0.09040157036671613
epoch - 234, loss: 0.09033575456377389
epoch - 235, loss: 0.09027027910448072
epoch - 236, loss: 0.09020513998013324
epoch - 237, loss: 0.09014033325855247
epoch - 238, loss: 0.09007585508217955
epoch - 239, loss: 0.09001170166622607
epoch - 240, loss: 0.08994786929687813
epoch - 241, loss: 0.0898843543295514
epoch - 242, loss: 0.08982115318719608
epoch - 243, loss: 0.08975826235865038
epoch - 244, loss: 0.08969567839704051
epoch - 245, loss: 0.08963339791822608
epoch - 246, loss: 0.08957141759928941
epoch - 247, loss: 0.08950973417706735
epoch - 248, loss: 0.08944834444672417
epoch - 249, loss: 0.08938724526036469
epoch - 250, loss: 0.0893264335256858
epoch - 251, loss: 0.0892659062046655
epoch - 252, loss: 0.08920566031228863
epoch - 253, loss: 0.08914569291530741
epoch - 254, loss: 0.08908600113103649
epoch - 255, loss: 0.08902658212618078
epoch - 256, loss: 0.08896743311569583
epoch - 257, loss: 0.08890855136167888
epoch - 258, loss: 0.08884993417229052
epoch - 259, loss: 0.08879157890070528
epoch - 260, loss: 0.08873348294409104
epoch - 261, loss: 0.0886756437426155
epoch - 262, loss: 0.08861805877847981
epoch - 263, loss: 0.08856072557497793
epoch - 264, loss: 0.08850364169558106
epoch - 265, loss: 0.08844680474304678
epoch - 266, loss: 0.0883902123585516
epoch - 267, loss: 0.08833386222084641
epoch - 268, loss: 0.08827775204543466
epoch - 269, loss: 0.08822187958377187
epoch - 270, loss: 0.08816624262248608
epoch - 271, loss: 0.088110838982619
epoch - 272, loss: 0.0880556665188866
epoch - 273, loss: 0.08800072311895935
epoch - 274, loss: 0.08794600670276065
epoch - 275, loss: 0.08789151522178379
epoch - 276, loss: 0.08783724665842613
epoch - 277, loss: 0.08778319902534083
epoch - 278, loss: 0.08772937036480463
epoch - 279, loss: 0.08767575874810224
epoch - 280, loss: 0.08762236227492609
epoch - 281, loss: 0.0875691790727913
epoch - 282, loss: 0.08751620729646561
epoch - 283, loss: 0.08746344512741341
epoch - 284, loss: 0.08741089077325405
epoch - 285, loss: 0.08735854246723325
epoch - 286, loss: 0.08730639846770803
epoch - 287, loss: 0.08725445705764437
epoch - 288, loss: 0.0872027165441272
epoch - 289, loss: 0.08715117525788245
epoch - 290, loss: 0.08709983155374552
epoch - 291, loss: 0.08704868380995416
epoch - 292, loss: 0.08699773042280956
epoch - 293, loss: 0.08694696981305411
epoch - 294, loss: 0.08689640042285166
epoch - 295, loss: 0.08684602071537535
epoch - 296, loss: 0.08679582917440554
epoch - 297, loss: 0.08674582430393725
epoch - 298, loss: 0.08669600462779674
epoch - 299, loss: 0.08664636868926787
epoch - 300, loss: 0.08659691505072642
epoch - 301, loss: 0.0865476422932841
epoch - 302, loss: 0.08649854901643989
epoch - 303, loss: 0.08644963383774039
epoch - 304, loss: 0.08640089539244773
epoch - 305, loss: 0.08635233233321517
epoch - 306, loss: 0.08630394332977047
epoch - 307, loss: 0.08625572706860637
epoch - 308, loss: 0.08620768225267836
epoch - 309, loss: 0.08615980760110915
epoch - 310, loss: 0.08611210184890028
epoch - 311, loss: 0.08606456374664986
epoch - 312, loss: 0.08601719206027704
epoch - 313, loss: 0.08596998557075264
epoch - 314, loss: 0.08592294307383566
epoch - 315, loss: 0.08587606337981596
epoch - 316, loss: 0.0858293453132625
epoch - 317, loss: 0.08578278771277735
epoch - 318, loss: 0.08573638943075494
epoch - 319, loss: 0.08569014933314682
epoch - 320, loss: 0.0856440662992315
epoch - 321, loss: 0.08559813922138938
epoch - 322, loss: 0.08555236700488249
epoch - 323, loss: 0.0855067485676392
epoch - 324, loss: 0.08546128284004337
epoch - 325, loss: 0.08541596876472826
epoch - 326, loss: 0.08537080529637472
epoch - 327, loss: 0.0853257914015137
epoch - 328, loss: 0.08528092605833307
epoch - 329, loss: 0.08523620825648846
epoch - 330, loss: 0.08519163699691812
epoch - 331, loss: 0.08514721129166165
epoch - 332, loss: 0.08510293016368257
epoch - 333, loss: 0.08505879264669457
epoch - 334, loss: 0.08501479778499127
epoch - 335, loss: 0.0849709446332799
epoch - 336, loss: 0.08492723225651767
epoch - 337, loss: 0.08488365972975238
epoch - 338, loss: 0.08484022613796563
epoch - 339, loss: 0.08479693057591939
epoch - 340, loss: 0.08475377214800583
epoch - 341, loss: 0.08471074996810019
epoch - 342, loss: 0.08466786315941621
epoch - 343, loss: 0.08462511085436504
epoch - 344, loss: 0.0845824921944165
epoch - 345, loss: 0.08454000632996332
epoch - 346, loss: 0.0844976524201879
epoch - 347, loss: 0.08445542963293202
epoch - 348, loss: 0.08441333714456861
epoch - 349, loss: 0.08437137413987646
epoch - 350, loss: 0.08432953981191717
epoch - 351, loss: 0.08428783336191445
epoch - 352, loss: 0.08424625399913581
epoch - 353, loss: 0.0842048009407765
epoch - 354, loss: 0.08416347341184577
epoch - 355, loss: 0.08412227064505502
epoch - 356, loss: 0.08408119188070845
epoch - 357, loss: 0.0840402363665953
epoch - 358, loss: 0.08399940335788462
epoch - 359, loss: 0.08395869211702159
epoch - 360, loss: 0.08391810191362609
epoch - 361, loss: 0.08387763202439283
epoch - 362, loss: 0.08383728173299362
epoch - 363, loss: 0.08379705032998126
epoch - 364, loss: 0.08375693711269515
epoch - 365, loss: 0.0837169413851689
epoch - 366, loss: 0.08367706245803921
epoch - 367, loss: 0.08363729964845663
epoch - 368, loss: 0.08359765227999805
epoch - 369, loss: 0.08355811968258038
epoch - 370, loss: 0.08351870119237613
epoch - 371, loss: 0.08347939615173033
epoch - 372, loss: 0.0834402039090788
epoch - 373, loss: 0.08340112381886812
epoch - 374, loss: 0.08336215524147685
epoch - 375, loss: 0.08332329754313804
epoch - 376, loss: 0.08328455009586333
epoch - 377, loss: 0.08324591227736806
epoch - 378, loss: 0.08320738347099797
epoch - 379, loss: 0.0831689630656568
epoch - 380, loss: 0.0831306504557355
epoch - 381, loss: 0.08309244504104259
epoch - 382, loss: 0.0830543462267352
epoch - 383, loss: 0.08301635342325199
epoch - 384, loss: 0.08297846604624673
epoch - 385, loss: 0.08294068351652309
epoch - 386, loss: 0.08290300525997056
epoch - 387, loss: 0.08286543070750145
epoch - 388, loss: 0.0828279592949888
epoch - 389, loss: 0.08279059046320551
epoch - 390, loss: 0.08275332365776421
epoch - 391, loss: 0.08271615832905833
epoch - 392, loss: 0.08267909393220405
epoch - 393, loss: 0.08264212992698314
epoch - 394, loss: 0.0826052657777867
epoch - 395, loss: 0.08256850095355996
epoch - 396, loss: 0.08253183492774786
epoch - 397, loss: 0.08249526717824135
epoch - 398, loss: 0.08245879718735229
epoch - 399, loss: 0.08242242444181093
epoch - 400, loss: 0.08238614843239311
epoch - 401, loss: 0.08234996865425527
epoch - 402, loss: 0.08231388460674448
epoch - 403, loss: 0.08227789579334971
epoch - 404, loss: 0.08224200172165382
epoch - 405, loss: 0.0822062019032863
epoch - 406, loss: 0.08217049585387677
epoch - 407, loss: 0.08213488309300915
epoch - 408, loss: 0.08209936314417648
epoch - 409, loss: 0.08206393553473659
epoch - 410, loss: 0.0820285997958682
epoch - 411, loss: 0.08199335546252787
epoch - 412, loss: 0.0819582020734075
epoch - 413, loss: 0.08192313917089245
epoch - 414, loss: 0.08188816630102035
epoch - 415, loss: 0.0818532830134405
epoch - 416, loss: 0.08181848886137368
epoch - 417, loss: 0.081783783401573
epoch - 418, loss: 0.08174916619428467
epoch - 419, loss: 0.08171463680321002
epoch - 420, loss: 0.08168019479546748
epoch - 421, loss: 0.08164583974155558
epoch - 422, loss: 0.0816115712153161
epoch - 423, loss: 0.08157738879389809
epoch - 424, loss: 0.08154329205772196
epoch - 425, loss: 0.08150928059044468
epoch - 426, loss: 0.08147535397892486
epoch - 427, loss: 0.0814415118131887
epoch - 428, loss: 0.08140775368639637
epoch - 429, loss: 0.08137407919480867
epoch - 430, loss: 0.08134048793775439
epoch - 431, loss: 0.08130697951759797
epoch - 432, loss: 0.08127355353970757
epoch - 433, loss: 0.0812402096124239
epoch - 434, loss: 0.08120694734702891
epoch - 435, loss: 0.08117376635771548
epoch - 436, loss: 0.08114066626155718
epoch - 437, loss: 0.08110764667847851
epoch - 438, loss: 0.08107470723122565
epoch - 439, loss: 0.08104184754533733
epoch - 440, loss: 0.08100906724911655
epoch - 441, loss: 0.08097636597360215
epoch - 442, loss: 0.08094374335254109
epoch - 443, loss: 0.08091119902236116
epoch - 444, loss: 0.08087873262214362
epoch - 445, loss: 0.08084634379359676
epoch - 446, loss: 0.08081403218102932
epoch - 447, loss: 0.08078179743132471
epoch - 448, loss: 0.08074963919391503
epoch - 449, loss: 0.08071755712075594
epoch - 450, loss: 0.08068555086630155
epoch - 451, loss: 0.08065362008747971
epoch - 452, loss: 0.08062176444366768
epoch - 453, loss: 0.08058998359666798
epoch - 454, loss: 0.08055827721068469
epoch - 455, loss: 0.08052664495229993
epoch - 456, loss: 0.08049508649126876
epoch - 457, loss: 0.08046360149908925
epoch - 458, loss: 0.0804321896482813
epoch - 459, loss: 0.08040085061471058
epoch - 460, loss: 0.0803695840765079
epoch - 461, loss: 0.08033838971411306
epoch - 462, loss: 0.08030726721111452
epoch - 463, loss: 0.08027621625124691
epoch - 464, loss: 0.08024523652148653
epoch - 465, loss: 0.08021432771096865
epoch - 466, loss: 0.080183489510967
epoch - 467, loss: 0.08015272161487376
epoch - 468, loss: 0.08012202371817935
epoch - 469, loss: 0.08009139551845296
epoch - 470, loss: 0.08006083671532295
epoch - 471, loss: 0.08003034701045768
epoch - 472, loss: 0.07999992610754637
epoch - 473, loss: 0.07996957371228053
epoch - 474, loss: 0.07993928953233521
epoch - 475, loss: 0.07990907327735078
epoch - 476, loss: 0.07987892465891477
epoch - 477, loss: 0.07984884339054404
epoch - 478, loss: 0.07981882918766696
epoch - 479, loss: 0.07978888176760598
epoch - 480, loss: 0.0797590008495605
epoch - 481, loss: 0.0797291861545895
epoch - 482, loss: 0.07969943740559492
epoch - 483, loss: 0.07966975432832142
epoch - 484, loss: 0.07964013664940983
epoch - 485, loss: 0.07961058409605573
epoch - 486, loss: 0.0795810963983677
epoch - 487, loss: 0.0795516732882158
epoch - 488, loss: 0.07952231449921564
epoch - 489, loss: 0.07949301976671289
epoch - 490, loss: 0.07946378882776788
epoch - 491, loss: 0.07943462142114048
epoch - 492, loss: 0.0794055172872749
epoch - 493, loss: 0.07937647616833853
epoch - 494, loss: 0.07934749780813072
epoch - 495, loss: 0.07931858195198065
epoch - 496, loss: 0.07928972834692317
epoch - 497, loss: 0.07926093674160492
epoch - 498, loss: 0.07923220688627013
epoch - 499, loss: 0.0792035385327469
epoch - 500, loss: 0.07917493143443324

In [53]:
#model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.6).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)

tensor(0.9825)

In [ ]:
for epoch in range(epochs):
    y_pred = self.we

SyntaxError: unexpected EOF while parsing (3688732500.py, line 1)

# autograd

In [2]:
import torch

In [13]:
x = torch.tensor(3, requires_grad= True, dtype = torch.float64)

In [14]:
y = x**2

In [15]:
y.backward()

In [16]:
y

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [17]:
print(x.grad)

tensor(6., dtype=torch.float64)

In [19]:
x = torch.tensor(6.8)
y = torch.tensor(1)

In [21]:
w = torch.tensor(1, requires_grad= True, dtype = torch.float32)
b = torch.tensor(0, requires_grad= True, dtype= torch.float32)

In [22]:
def binary_cross_entropy(prediction, target):
    epsilon = 1e-8
    pred = torch.clamp(prediction, epsilon, 1 - epsilon)
    prediction = -(target* torch.log(pred) + (1- target) * torch.log(1 - pred))
    return prediction

In [23]:
#forward pass 
z = w * x + b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy(y_pred, y)

In [24]:
loss

tensor(0.0011, grad_fn=<NegBackward0>)

In [26]:
x = torch.tensor([1, 2 , 3], requires_grad= True, dtype = torch.float32)

In [27]:
y = (x**2).mean()

In [28]:
y.backward()

In [29]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [30]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

# using torch.nn to create model

In [31]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [32]:
features = torch.rand(10, 5)

# model object
model = SimpleNN(features.shape[1])

#model call for forward pass
model(features)

tensor([[0.4867],
        [0.5867],
        [0.4982],
        [0.5879],
        [0.5319],
        [0.5271],
        [0.6339],
        [0.5291],
        [0.5630],
        [0.5658]], grad_fn=<SigmoidBackward0>)

In [33]:

#weight and bias in linear layer
model.linear.weight

Parameter containing:
tensor([[ 0.1518, -0.1320, -0.3146,  0.2978,  0.3107]], requires_grad=True)

In [34]:
model.linear.bias

Parameter containing:
tensor([0.0767], requires_grad=True)

In [35]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [37]:
from torchinfo import summary
summary(model, input_size = (10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
SimpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [ ]:
# now create a NN with a hidden layer with 3 neurons and relu then sigmoid on final layer

In [46]:
class MLP(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

In [47]:
mlp = MLP(features.shape[1])

In [48]:
mlp(features)

In [49]:
mlp.linear1.weight

Parameter containing:
tensor([[ 0.4101,  0.2632, -0.0970,  0.0431, -0.3354],
        [-0.3705,  0.2177,  0.0926, -0.3017, -0.0518],
        [ 0.4374, -0.2026, -0.1898, -0.1137, -0.2194]], requires_grad=True)

In [50]:
mlp.linear1.bias

Parameter containing:
tensor([ 0.0446,  0.3816, -0.3284], requires_grad=True)

In [39]:
# using container to write this
class MLP(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [51]:
summary(mlp, input_size= (10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MLP                                      --                        --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================